### ISSUE TITLE
Advanced Binding with Type Checking

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/arena#32]
Now in Arena's xtend versions you can add check typing like this:

```java
new TextBox(mainPanel) => [
			value <=> "valor"
			enabled <=> [ CalculadoraBigDecimal calc | calc.habilitado ]
```

But you can't transform that property inside the closure:

```java
new TextBox(mainPanel) => [
			value <=> "valor"
			enabled <=> [ CalculadoraBigDecimal calc | calc.valor != 2 ]
```
Because you get an exception:

```
java.lang.ClassCastException: java.math.BigDecimal cannot be cast to java.lang.Boolean
	at org.eclipse.jface.internal.databinding.swt.TextEditableObservableValue.doSetValue(TextEditableObservableValue.java:67)
	at org.eclipse.core.databinding.observable.value.AbstractObservableValue.setValue(AbstractObservableValue.java:55)
	at org.uqbar.ui.jface.base.BaseUpdateValueStrategy.doSet(BaseUpdateValueStrategy.java:37)
	at org.eclipse.core.databinding.ValueBinding$4.run(ValueBinding.java:184)
```
That's because operator_spaceship defines the following operation:

```java
def static <M,R> operator_spaceship(ViewObservable obs, Function1<M,R> propertyBinder) {
       obs <=> calculateObservable(obs.view.containerModelObject, propertyBinder)
}
```
calculateObservable searches for a property, 
```java
	def static <M,R> calculateObservable(Object model, Function1<M, R> propertyBinder) {
		val Class<M> concreteModelType = model.class as Class<M>
		val handler = createInvocationHandler()
		val M mock = createMockFor(concreteModelType, handler) 
		
		// call closure
		propertyBinder.apply(mock)
		
		//TODO: inspect mock for getter calls, register binding.
		handler.getPropertyName
	}
```

For the above example calculateObservable returns at runtime:
property: valor
value: a boolean value, which is not compatible (thus resulting in a class cast exception).

It should be nice to transform the value in the closure.

**Comment by fdodino** [comment]
@PalumboN is this related to your request?

**Comment by PalumboN** [comment]
Yeah!

**Comment by fdodino** [comment]
Well I think it is hard to solve this and also it fosters students to move business decision (that now relay on domain objects) to UI concern. So after several hours, I decided to wait to address this until next occasion.
