### ISSUE TITLE
Ugly exception when view model is not @Observable

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/arena#33]
Same as https://github.com/uqbar-project/arena/issues/19 should also enhance explanation for windows

**Comment by fdodino** [comment]
Well, now I added this validation in Window main class

```xtend
	/**
	 * New method added for validation before showing
	 * Now you can't open a window if its model is not a class annotated with @Observable 
	 * 
	 * @since 3.6.2
	 * 
	 */
	public void validate() {
		Class<?> clazz = this.getModelObject().getClass();
		if (!clazz.isAnnotationPresent(ObservableAnnotation)) {
			throw new RuntimeException("La clase " + clazz.getName() + " no tiene la annotation " + ObservableAnnotation.getSimpleName() + " que es necesaria para ser modelo de una vista en Arena");
		}
	}
```

which produces a Window with a Model not annotated with Observable this runtime error:

```
Exception in thread "main" java.lang.RuntimeException: La clase org.uqbar.arena.examples.controls.FacturaNoObservable no tiene la annotation Observable que es necesaria para ser modelo de una vista en Arena
	at org.uqbar.arena.windows.Window.validate(Window.java:213)
	at org.uqbar.arena.windows.Window.createContents(Window.java:113)
	at org.uqbar.arena.windows.Window.open(Window.java:142)
	at org.uqbar.arena.Application.run(Application.java:85)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:288)
	at org.uqbar.arena.jface.app.JFaceApplicationBuilder.run(JFaceApplicationBuilder.scala:18)
	at org.uqbar.arena.Application.start(Application.java:64)
	at org.uqbar.arena.windows.MainWindow.startApplication(MainWindow.java:30)
	at org.uqbar.arena.examples.controls.binding.enable.FacturaWindow.main(FacturaWindow.java:25)
```

So **it fails to open**, previously it opened but binding wasn't supported.
I prefer not to show instead of silently output an error in console (error that students and also teacher don't see at first glance).
It is a special decision I'd like to agree with @tinchodias  @estefaniamiguel @PalumboN @grisoliarodrigo 
What do you think?

**Comment by tinchodias** [comment]
I like it!

**Comment by PalumboN** [comment]
👌
