### ISSUE TITLE
Defining a reference to a List defined by [] shortcut in Xtend results in a strange scala.List error

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/arena#39]
Define a model with a List binding, initalize using [] then at runtime you see a strange scala.List binding error. See votacion example, in getZonas method, replace the default by [] and you get that error.

**Comment by fdodino** [comment]
Error is 

```
Exception in thread "main" java.lang.UnsupportedOperationException: Cannot convert scala collection type class ar.edu.votacion.Encuesta$$Lambda$9/919962315 to Java Collection
	at org.uqbar.lacar.ui.impl.jface.bindings.ScalaJavaListConverter.convertScalaCollectionToJavaIfNeeded(ScalaJavaObservableList.scala:20)
	at org.uqbar.lacar.ui.impl.jface.bindings.ArenaJavaBeanObservableSet.primGetValues(ArenaJavaBeanObservableSet.java:89)
	at org.uqbar.lacar.ui.impl.jface.bindings.ArenaJavaBeanObservableSet.getValues(ArenaJavaBeanObservableSet.java:102)
	at org.uqbar.lacar.ui.impl.jface.bindings.ArenaJavaBeanObservableSet.<init>(ArenaJavaBeanObservableSet.java:79)
	at org.uqbar.lacar.ui.impl.jface.bindings.ArenaJavaBeanObservableSet.<init>(ArenaJavaBeanObservableSet.java:45)
	at org.uqbar.lacar.ui.impl.jface.bindings.JavaBeanTransacionalObservableSet.<init>(JavaBeanTransacionalObservableSet.java:19)
	at org.uqbar.lacar.ui.impl.jface.bindings.JFaceObservableFactory.observeSet(JFaceObservableFactory.java:74)
	at org.uqbar.lacar.ui.impl.jface.bindings.JFaceObservableFactory.observeSet(JFaceObservableFactory.java:67)
	at org.uqbar.lacar.ui.impl.jface.lists.JFaceListItemsBindingBuilder.observeProperty(JFaceListItemsBindingBuilder.java:34)
	at org.uqbar.arena.bindings.ObservableProperty.configure(ObservableProperty.java:66)
	at org.uqbar.lacar.ui.model.bindings.Binding.execute(Binding.java:110)
	at org.uqbar.arena.widgets.Widget.showOn(Widget.java:95)
	at org.uqbar.arena.widgets.Panel.showOn(Panel.java:140)
	at org.uqbar.arena.windows.Window.showOn(Window.java:197)
	at org.uqbar.arena.windows.Window.showOn(Window.java:25)
	at org.uqbar.lacar.ui.impl.jface.builder.windows.JFaceWindowBuilder.createWindowContents(JFaceWindowBuilder.scala:89)
	at org.uqbar.lacar.ui.impl.jface.builder.windows.JFaceWindowBuilder$$anon$1.createContents(JFaceWindowBuilder.scala:146)
	at org.uqbar.lacar.ui.impl.jface.builder.windows.JFaceWindowBuilder$$anon$1.createContents(JFaceWindowBuilder.scala:144)
	at org.eclipse.jface.window.Window.create(Window.java:431)
	at org.uqbar.lacar.ui.impl.jface.builder.windows.JFaceWindowBuilder.open(JFaceWindowBuilder.scala:55)
	at org.uqbar.arena.windows.Window.open(Window.java:145)
	at org.uqbar.arena.Application.run(Application.java:85)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:288)
	at org.uqbar.arena.jface.app.JFaceApplicationBuilder.run(JFaceApplicationBuilder.scala:18)
	at org.uqbar.arena.Application.start(Application.java:64)
	at org.uqbar.arena.windows.MainWindow.startApplication(MainWindow.java:30)
	at ar.edu.votacion.EncuestaWindow.main(EncuestaWindow.java:35)
```

See branch "Reproducing issue #39"

**Comment by fdodino** [comment]
Oh, oh, my fault @PalumboN @grisoliarodrigo !

[ ] denotes a Lambda, exactly what stack trace described.
I should have use this shortcuts: #{} for sets or #[ ] for lists

Closing this issue.
