### ISSUE TITLE
Strange error in firePropertyChange when defining a variable as "protected"

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/arena#54]
See [link to this branch](https://github.com/algo2-unsam/tp-eventos-2018-grupo-3/tree/conflictiva). UI project is [this](https://github.com/algo3-unsam/tp-eventos-arena-grupo-03-1/tree/conflictiva)

![image](https://user-images.githubusercontent.com/4549002/44356457-c525e200-a485-11e8-9b11-bb41ea852679.png)

```
Exception in thread "main" javassist.CannotCompileException: [source error] firePropertyChange(java.lang.String,edu.unsam.tpeventos2018.grupo3.Usuario,edu.unsam.tpeventos2018.grupo3.Usuario) not found in edu.unsam.tpeventos2018.grupo3.Evento
at javassist.expr.FieldAccess.replace(FieldAccess.java:216)
at org.uqbar.apo.Advice.edit(Advice.scala:47)
at javassist.expr.ExprEditor.loopBody(ExprEditor.java:198)
at javassist.expr.ExprEditor.doit(ExprEditor.java:91)
at javassist.CtClassType.instrument(CtClassType.java:1398)
at org.uqbar.apo.Advice.apply(Advice.scala:83)
at org.uqbar.poo.aop.ObservableConfiguration$$anon$2.apply(ObservableConfiguration.scala:28)
at org.uqbar.apo.AdviceWeaver.applyAdviceToCtClass(AdviceWeaver.scala:42)
at org.uqbar.apo.AdviceWeaver$$anonfun$applyAdvice$1.apply(AdviceWeaver.scala:35)
at org.uqbar.apo.AdviceWeaver$$anonfun$applyAdvice$1.apply(AdviceWeaver.scala:33)
at scala.collection.immutable.List.foreach(List.scala:381)
at org.uqbar.apo.AdviceWeaver.applyAdvice(AdviceWeaver.scala:33)
at org.uqbar.apo.APOClassLoader.applyAPO(APOClassLoader.scala:106)
at org.uqbar.apo.APOClassLoader.findClass(APOClassLoader.scala:83)
at org.uqbar.apo.APOClassLoader.loadClass(APOClassLoader.scala:58)
at java.lang.ClassLoader.loadClass(Unknown Source)
at org.uqbar.apo.APOClassLoader.loadClass(APOClassLoader.scala:69)
at jose.RealmenteNoSeQuePasa.main(RealmenteNoSeQuePasa.java:20)
Caused by: compile error: firePropertyChange(java.lang.String,edu.unsam.tpeventos2018.grupo3.Usuario,edu.unsam.tpeventos2018.grupo3.Usuario) not found in edu.unsam.tpeventos2018.grupo3.Evento
at javassist.compiler.TypeChecker.atMethodCallCore(TypeChecker.java:723)
at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:688)
at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:157)
at javassist.compiler.ast.CallExpr.accept(CallExpr.java:46)
at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:242)
at javassist.compiler.CodeGen.atStmnt(CodeGen.java:330)
at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
at javassist.compiler.Javac.compileStmnt(Javac.java:569)
at javassist.expr.FieldAccess.replace(FieldAccess.java:210)
... 17 more
```

Cosas que probé:

- Utilizar como modelo una clase creada en el mismo proyecto de Arena y funciona
- Utilizar como modelo otra clase del dominio del año pasado exactamente igual que utilizo esta y funciona (utilizo Locacion y funciona!!!)
- No es un problema del settings.xml
- No es un problema del @Observable
- No es un problema de dependencias porque como mencioné con otras clases si anda... y ahí va un Screen que lo prueba

![image](https://user-images.githubusercontent.com/4549002/44356466-ceaf4a00-a485-11e8-9841-076e0f5cfefc.png)

Hay novedades. 
Si extiendo la clase Usuario y uso esa clase como dominio, anda..

```xtend
package edu.unsam.tpeventos2018.grupo3

import edu.unsam.tpeventos2018.grupo3.Usuario
import org.uqbar.commons.model.annotations.Observable

@Observable
class UsuarioExtendido extends Usuario {
}
```

**Comment by fdodino** [comment]
El problema se daba porque definió una variable de tipo protected, deberíamos ver que no tire ese error sino: "el accessor debe ser público, evite definir variables protected".
